version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_monitor_app
    restart: always
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POLL_INTERVAL: ${POLL_INTERVAL:-300}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: github_monitor_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      #POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
